fix failover if no files or main image
matthew1809/ReactRedux pull request #32
Opened 2017-08-17 16:30 UTC by matthew1809

Add if else logic within the `isThereAFile` function to stop it dying if there's no data file object in the relationships for products.

2017-08-25 13:01 UTC, ynnoj requested changes

2017-08-25 13:01 UTC, ynnoj commented on src/components/Products/ProductImage.js
> +      if(this.props.product.relationships.files) {
We should use the `product` object passed into `isThereAFile()` as an argument, or remove the parameter on line 44.

2017-08-25 13:01 UTC, ynnoj commented on src/components/Products/ProductImage.js
> +      if(this.props.product.relationships.files) {
☝️ Same applies to the `isThereAMainImage()` function.

2017-08-25 13:01 UTC, ynnoj commented on src/components/Products/ProductImage.js
> +          return <img alt={this.props.product.name + ', ' + this.props.product.description} src={file.link.href} style={{"background": this.props.background}}/>
I can see [instances](https://github.com/moltin/react-demo-store/blob/2b25d145ef472d6effa22e2af84e4153a891d5ca/src/components/Products/AllProducts.js#L36) where the `ProductImage` component is invoked without a `background` property. What happens in those cases?

2018-01-06 11:20 UTC, matthew1809 commented
Closing in favour on changes on branch https://github.com/moltin/react-demo-store/tree/fix%2Fgracefully-handle-responses

2018-01-06 11:20 UTC, closed without merging